### ISSUE TITLE
Renewing tokens

### ISSUE THREAD

**Issue by dbrgn** [pimeys/apns2#15]
In the README you write:

> If using a token connection, the connection should handle renewal of the signature before it's too late and for now I haven't seen any errors related to invalid tokens.

Is the lifetime of the JWT token tracked somehow? Is it the responsibility of the user to renew the signature? If yes, is there a way to renew the signature without recreating a client instance?

If this isn't being done yet, could this crate register a timer to auto-renew the signature, so that the user doesn't have to deal with it anymore?

**Comment by pimeys** [comment]
No, the signature is automatically renewed. Apple [tells](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html) one hour, we do [45 minutes](https://github.com/pimeys/apns2/blob/master/src/client.rs#L112) to be on the safe side.

It is all automatic and thread-safe, I should probably rethink the README.

**Comment by dbrgn** [comment]
Ah, I misread the readme. It says "the connection should handle". That was a statement, not a requirement towards the user :smile: Sorry.

**Comment by pimeys** [comment]
The documentation can always be better. I'm not a native English speaker, so corrections are appreciated.
