### ISSUE TITLE
Client: Generic type arguments

### ISSUE THREAD

**Issue by dbrgn** [pimeys/apns2#4]
Edit: Sorry, submitted too early due to a new keyboard :)

The Client::token signature currently looks like this:

```rust
    pub fn token<S, R>(
        pkcs8_pem: R,
        key_id: S,
        team_id: S,
        handle: &Handle,
        endpoint: Endpoint,
    ) -> Result<Client, Error>
    where
        S: Into<String>,
        R: Read,
{
```

This requires that key_id and team_id have the *same* type that implements Into<String>.

What you want is probably this:

```rust
    pub fn token<S, R>(
        pkcs8_pem: R,
        key_id: S,
        team_id: T,
        handle: &Handle,
        endpoint: Endpoint,
    ) -> Result<Client, Error>
    where
        S: Into<String>,
        T: Into<String>,
        R: Read,
{
```

This way, the two types can differ, as long as they both impl Into<String>.

**Comment by dbrgn** [comment]
Also, `ToString` (https://doc.rust-lang.org/std/string/trait.ToString.html) *might* be more appropriate than `Into<String>`, but I'm not 100% sure about that.

**Comment by pimeys** [comment]
A good point. I'll make the changes tomorrow when I have some time.

**Comment by pimeys** [comment]
Changed. I'll stick with the `Into` because I don't see much reason for `ToString` here. Yeah, of course the main use case here is to allow using `&str` or `String`, not that much anything else. Maybe even `Cow` would suffice.

**Comment by dbrgn** [comment]
You do need an owned/allocated version of the string though, right?

I think Into is fine.

**Comment by pimeys** [comment]
Yeah, you keep the client alive a long time so forcing it into a lifetime doesn't make sense. Also you hopefully create connections rarely, so allocating from the heap doesn't hurt.
